# Generated by Django 5.1.3 on 2024-11-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=25)),
                ("cost", models.DecimalField(decimal_places=3, max_digits=5)),
                ("date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
    ]
