# Generated by Django 5.1.3 on 2024-11-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
